const json=(o,status=200,extra={})=>new Response(JSON.stringify(o),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store',...extra}});
const enc=new TextEncoder(), dec=new TextDecoder();
const id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const unb64=s=>{s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
async function sha(s){return b64(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function pbkdf(password,salt){const k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return b64(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:310000,hash:'SHA-256'},k,256))}
async function encryptText(text,key){const iv=crypto.getRandomValues(new Uint8Array(12));const k=await crypto.subtle.importKey('raw',enc.encode(key),{name:'AES-GCM'},false,['encrypt']);const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(text));return b64(iv)+'.'+b64(ct)}
async function decryptText(blob,key){try{const [iv,ct]=blob.split('.');const k=await crypto.subtle.importKey('raw',enc.encode(key),{name:'AES-GCM'},false,['decrypt']);return dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},k,unb64(ct)))}catch{return null}}
async function body(r){try{return await r.json()}catch{return {}}}
const normPhone=p=>String(p||'').replace(/[^0-9+]/g,'');
function cookie(name,val,opts=''){return `${name}=${val}; Path=/; HttpOnly; Secure; SameSite=Strict; ${opts}`}
function getCookie(r,n){const c=r.headers.get('Cookie')||'';return c.split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='))?.slice(n.length+1)||null}
async function audit(env,uid,action,r){const ip=r.headers.get('CF-Connecting-IP')||'';await env.DB.prepare('INSERT INTO audit(id,user_id,action,ip,created_at) VALUES(?,?,?,?,?)').bind(id(),uid,action,ip,now()).run()}
async function init(env){
  const n=await env.DB.prepare("SELECT COUNT(*) n FROM users WHERE role='teacher'").first();
  if(!n?.n && env.TEACHER_PHONE){const phone=normPhone(env.TEACHER_PHONE), key=env.APP_SECRET||'TEMP';await env.DB.prepare('INSERT INTO users(id,role,name,phone_hash,phone_enc,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id(),'teacher',env.TEACHER_NAME||'علیرضا صدوقی چنار',await sha(phone),await encryptText(phone,key),1,now(),now()).run()}
  const c=await env.DB.prepare('SELECT COUNT(*) n FROM classes').first();
  if(!c?.n){for(let g=1;g<=6;g++)for(const s of ['A','B'])await env.DB.prepare('INSERT INTO classes(id,grade,name) VALUES(?,?,?)').bind(id(),g,`${g}${s}`).run()}
}
async function session(env,r){const raw=getCookie(r,'sid');if(!raw)return null;const th=await sha(raw);return env.DB.prepare('SELECT s.*,u.role,u.name,u.phone_hash FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked=0 AND s.expires_at>? AND u.active=1').bind(th,Date.now()).first()}
async function auth(env,r,roles=[]){const s=await session(env,r);if(!s)return {err:json({error:'unauthorized'},401)};if(roles.length&&!roles.includes(s.role))return {err:json({error:'forbidden'},403)};if(r.method!=='GET'&&r.method!=='HEAD'&&r.headers.get('X-CSRF-Token')!==s.csrf_token)return {err:json({error:'csrf'},403)};return {s}}
async function loginSession(env,u,r){const raw=b64(crypto.getRandomValues(new Uint8Array(32))),csrf=b64(crypto.getRandomValues(new Uint8Array(24)));await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,csrf_token,expires_at,revoked,created_at) VALUES(?,?,?,?,?,?,?)').bind(id(),u.id,await sha(raw),csrf,Date.now()+86400000,0,now()).run();await audit(env,u.id,'LOGIN',r);return json({ok:true,role:u.role,name:u.name,csrf},200,{'Set-Cookie':cookie('sid',raw,'Max-Age=86400')})}
function teacherOnly(a){return !a.err&&['admin','teacher'].includes(a.s.role)}
async function visibleStudent(env,a,sid){if(['admin','teacher'].includes(a.s.role))return true;const row=await env.DB.prepare('SELECT user_id,guardian_phone_hash FROM students WHERE id=?').bind(sid).first();if(!row)return false;if(a.s.role==='student')return row.user_id===a.s.user_id;if(a.s.role==='parent')return row.guardian_phone_hash===a.s.phone_hash;return false}
async function api(env,r){const u=new URL(r.url),p=u.pathname;await init(env);
 if(r.method==='GET'&&p==='/api/health')return json({ok:true,version:'cloudflare-d1-final'});
 if(r.method==='POST'&&p==='/api/auth/request-otp'){const b=await body(r),phone=normPhone(b.phone),ph=await sha(phone);const user=await env.DB.prepare('SELECT * FROM users WHERE phone_hash=? AND active=1').bind(ph).first();if(!user)return json({error:'کاربر پیدا نشد'},404);const recent=await env.DB.prepare("SELECT COUNT(*) n FROM otps WHERE phone_hash=? AND created_at>?").bind(ph,new Date(Date.now()-60000).toISOString()).first();if((recent?.n||0)>=3)return json({error:'تعداد درخواست OTP زیاد است'},429);const code=env.DEV_OTP==='1'?'123456':String(Math.floor(100000+Math.random()*900000));await env.DB.prepare('INSERT INTO otps(id,user_id,phone_hash,code_hash,expires_at,used,purpose,attempts,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id(),user.id,ph,await sha(code),Date.now()+120000,0,'login',0,now()).run();return json({ok:true,devOtp:env.DEV_OTP==='1'?code:undefined})}
 if(r.method==='POST'&&p==='/api/auth/verify-otp'){const b=await body(r),ph=await sha(normPhone(b.phone)),o=await env.DB.prepare('SELECT * FROM otps WHERE phone_hash=? AND purpose=? AND used=0 ORDER BY created_at DESC LIMIT 1').bind(ph,'login').first();if(!o||Date.now()>o.expires_at||o.attempts>=5||await sha(String(b.code||''))!==o.code_hash){if(o)await env.DB.prepare('UPDATE otps SET attempts=attempts+1 WHERE id=?').bind(o.id).run();return json({error:'کد OTP نادرست یا منقضی است'},401)}await env.DB.prepare('UPDATE otps SET used=1 WHERE id=?').bind(o.id).run();const user=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(o.user_id).first();if(!user.password_hash)return json({ok:true,setupRequired:true,userId:user.id});return loginSession(env,user,r)}
 if(r.method==='POST'&&p==='/api/auth/set-password'){const b=await body(r);if(!b.userId||String(b.password||'').length<8)return json({error:'رمز باید حداقل ۸ کاراکتر باشد'},400);const u=await env.DB.prepare('SELECT * FROM users WHERE id=? AND active=1').bind(b.userId).first();if(!u)return json({error:'کاربر پیدا نشد'},404);const salt=b64(crypto.getRandomValues(new Uint8Array(16))),ph=await pbkdf(String(b.password),salt);await env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').bind(ph,salt,now(),u.id).run();return loginSession(env,u,r)}
 if(r.method==='POST'&&p==='/api/auth/login'){const b=await body(r),ph=await sha(normPhone(b.phone)),u=await env.DB.prepare('SELECT * FROM users WHERE phone_hash=? AND active=1').bind(ph).first();if(!u?.password_hash)return json({error:'اطلاعات ورود نادرست'},401);if(await pbkdf(String(b.password||''),u.password_salt)!==u.password_hash){await audit(env,u.id,'LOGIN_FAIL',r);return json({error:'اطلاعات ورود نادرست'},401)}return loginSession(env,u,r)}
 if(r.method==='POST'&&p==='/api/auth/logout'){const a=await auth(env,r);if(a.err)return a.err;await env.DB.prepare('UPDATE sessions SET revoked=1 WHERE id=?').bind(a.s.id).run();return json({ok:true},200,{'Set-Cookie':cookie('sid','deleted','Max-Age=0')})}
 if(r.method==='GET'&&p==='/api/me'){const a=await auth(env,r);if(a.err)return a.err;return json({id:a.s.user_id,role:a.s.role,name:a.s.name,csrf:a.s.csrf_token})}
 if(r.method==='GET'&&p==='/api/classes'){return json({classes:(await env.DB.prepare('SELECT * FROM classes ORDER BY grade,name').all()).results})}
 if(r.method==='GET'&&p==='/api/students'){const a=await auth(env,r,['admin','teacher','parent','student']);if(a.err)return a.err;const rows=(await env.DB.prepare('SELECT id,user_id,class_id,name_enc,national_id_enc,guardian_phone_enc,guardian_phone_hash,updated_at FROM students ORDER BY updated_at DESC').all()).results,key=env.APP_SECRET||'';const out=[];for(const x of rows){if(await visibleStudent(env,a,x.id))out.push({id:x.id,userId:x.user_id,classId:x.class_id,name:await decryptText(x.name_enc,key),nationalId:x.national_id_enc?await decryptText(x.national_id_enc,key):null,guardianPhone:a.s.role==='parent'?null:(x.guardian_phone_enc?await decryptText(x.guardian_phone_enc,key):null),updatedAt:x.updated_at})}return json({students:out})}
 if(r.method==='POST'&&p==='/api/students'){const a=await auth(env,r,['admin','teacher']);if(a.err)return a.err;const b=await body(r),key=env.APP_SECRET||'';if(!key||!b.name)return json({error:'APP_SECRET و نام دانش‌آموز لازم است'},400);const sid=id(),gp=normPhone(b.guardianPhone||'');await env.DB.prepare('INSERT INTO students(id,user_id,class_id,name_enc,national_id_enc,guardian_phone_enc,guardian_phone_hash,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(sid,b.userId||null,b.classId||null,await encryptText(b.name,key),b.nationalId?await encryptText(b.nationalId,key):null,gp?await encryptText(gp,key):null,gp?await sha(gp):null,now()).run();await audit(env,a.s.user_id,'CREATE_STUDENT',r);return json({id:sid},201)}
 const table={attendance:'attendance',evaluations:'evaluations','home-activities':'home_activities'};
 for(const [slug,t] of Object.entries(table)){if(r.method==='GET'&&p===`/api/${slug}`){const a=await auth(env,r);if(a.err)return a.err;const sid=u.searchParams.get('studentId');if(sid&&!(await visibleStudent(env,a,sid)))return json({error:'forbidden'},403);let q=`SELECT * FROM ${t}`;const binds=[];if(sid){q+=' WHERE student_id=?';binds.push(sid)}q+=' ORDER BY date DESC LIMIT 500';return json({items:(await env.DB.prepare(q).bind(...binds).all()).results})}}
 if(r.method==='POST'&&p==='/api/attendance'){const a=await auth(env,r,['admin','teacher']);if(a.err)return a.err;const b=await body(r);await env.DB.prepare('INSERT INTO attendance(id,student_id,date,status,note,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(student_id,date) DO UPDATE SET status=excluded.status,note=excluded.note,updated_at=excluded.updated_at').bind(id(),b.studentId,b.date,b.status,b.note||'',now()).run();return json({ok:true},201)}
 if(r.method==='POST'&&p==='/api/evaluations'){const a=await auth(env,r,['admin','teacher']);if(a.err)return a.err;const b=await body(r);await env.DB.prepare('INSERT INTO evaluations(id,student_id,subject,date,type,value,note,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id(),b.studentId,b.subject,b.date,b.type,b.value||'',b.note||'',now()).run();return json({ok:true},201)}
 if(r.method==='POST'&&p==='/api/home-activities'){const a=await auth(env,r,['admin','teacher']);if(a.err)return a.err;const b=await body(r);await env.DB.prepare('INSERT INTO home_activities(id,student_id,date,subject,duration,lesson,strength,note,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id(),b.studentId,b.date,b.subject,Number(b.duration||0),b.lesson||'',b.strength||'',b.note||'',now()).run();return json({ok:true},201)}
 if(r.method==='GET'&&p==='/api/assignments'){const a=await auth(env,r);if(a.err)return a.err;return json({items:(await env.DB.prepare('SELECT * FROM assignments ORDER BY updated_at DESC').all()).results})}
 if(r.method==='POST'&&p==='/api/assignments'){const a=await auth(env,r,['admin','teacher']);if(a.err)return a.err;const b=await body(r);await env.DB.prepare('INSERT INTO assignments(id,subject,title,due_date,description,created_by,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id(),b.subject,b.title,b.dueDate||'',b.description||'',a.s.user_id,now()).run();return json({ok:true},201)}
 if(r.method==='GET'&&p==='/api/resources'){const a=await auth(env,r);if(a.err)return a.err;return json({items:(await env.DB.prepare('SELECT * FROM resources ORDER BY updated_at DESC').all()).results})}
 if(r.method==='POST'&&p==='/api/resources'){const a=await auth(env,r,['admin','teacher']);if(a.err)return a.err;const b=await body(r);await env.DB.prepare('INSERT INTO resources(id,subject,title,type,url,description,created_by,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id(),b.subject,b.title,b.type||'',b.url||'',b.description||'',a.s.user_id,now()).run();return json({ok:true},201)}
 if(r.method==='GET'&&p==='/api/reports/student'){const a=await auth(env,r);if(a.err)return a.err;const sid=u.searchParams.get('studentId');if(!sid||!(await visibleStudent(env,a,sid)))return json({error:'forbidden'},403);const [attendance,evaluations,homeActivities]=await Promise.all([env.DB.prepare('SELECT * FROM attendance WHERE student_id=? ORDER BY date DESC').bind(sid).all(),env.DB.prepare('SELECT * FROM evaluations WHERE student_id=? ORDER BY date DESC').bind(sid).all(),env.DB.prepare('SELECT * FROM home_activities WHERE student_id=? ORDER BY date DESC').bind(sid).all()]);return json({attendance:attendance.results,evaluations:evaluations.results,homeActivities:homeActivities.results})}
 if(r.method==='POST'&&p==='/api/sync/push'){const a=await auth(env,r);if(a.err)return a.err;if(!['admin','teacher'].includes(a.s.role))return json({error:'offline sync write access denied'},403);const b=await body(r);let accepted=0;for(const c of (b.changes||[]).slice(0,100)){if(!c.id||!c.entity||!c.payload)continue;const sid=c.payload.studentId;if(!sid||!(await visibleStudent(env,a,sid)))continue;const ts=c.updatedAt||now();if(c.entity==='attendance'){await env.DB.prepare('INSERT INTO attendance(id,student_id,date,status,note,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(student_id,date) DO UPDATE SET status=excluded.status,note=excluded.note,updated_at=excluded.updated_at WHERE excluded.updated_at>attendance.updated_at').bind(c.entityId||id(),sid,c.payload.date,c.payload.status,c.payload.note||'',ts).run()}else if(c.entity==='evaluation'){await env.DB.prepare('INSERT INTO evaluations(id,student_id,subject,date,type,value,note,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET subject=excluded.subject,date=excluded.date,type=excluded.type,value=excluded.value,note=excluded.note,updated_at=excluded.updated_at WHERE excluded.updated_at>evaluations.updated_at').bind(c.entityId||id(),sid,c.payload.subject,c.payload.date,c.payload.type,c.payload.value||'',c.payload.note||'',ts).run()}else if(c.entity==='home_activity'){await env.DB.prepare('INSERT INTO home_activities(id,student_id,date,subject,duration,lesson,strength,note,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET date=excluded.date,subject=excluded.subject,duration=excluded.duration,lesson=excluded.lesson,strength=excluded.strength,note=excluded.note,updated_at=excluded.updated_at WHERE excluded.updated_at>home_activities.updated_at').bind(c.entityId||id(),sid,c.payload.date,c.payload.subject,Number(c.payload.duration||0),c.payload.lesson||'',c.payload.strength||'',c.payload.note||'',ts).run()}else continue;await env.DB.prepare('INSERT OR IGNORE INTO changes(id,entity,entity_id,payload,updated_at) VALUES(?,?,?,?,?)').bind(c.id,c.entity,c.entityId||'',JSON.stringify(c.payload),ts).run();accepted++}return json({ok:true,accepted})}
 if(r.method==='GET'&&p==='/api/sync/pull'){const a=await auth(env,r);if(a.err)return a.err;const since=u.searchParams.get('since')||'';return json({changes:(await env.DB.prepare('SELECT * FROM changes WHERE updated_at>? ORDER BY updated_at ASC LIMIT 500').bind(since).all()).results})}
 return json({error:'not found'},404)
}
export default {async fetch(r,env){try{return await api(env,r)}catch(e){console.error(e);return json({error:'server error'},500)}}};
