name = "virtual-school"
main = "worker.js"
compatibility_date = "2026-09-29"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "virtual-school-db"
database_id = "15ada409-a300-4f2e-a9bc-a600f9b84037""
migrations_dir = "migrations"

[vars]
TEACHER_NAME = "علیرضا صدوقی چنار"
